function dat=importfiledata(fileToRead1,n)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 28-Feb-2010 19:54:44

% Import the file
rawData1 = importdata(fileToRead1);
%rawData1 = dlmread(fileToRead1);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.

[unused,name] = fileparts(fileToRead1);
 
newData1.(genvarname(name)) = rawData1;

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
% Maximal time, FreeFem saves the fields in a long vector at each "n" iteration, 
% with the frequency of saving  
% np=rawData1(1,4)
  np=1;   % np = 1, when we have only one timestep saved

% nb of vertices
nx=rawData1(1,5)

i=0;
% Spatial filds on each column vs time 
for j=1:((np)/n)
    dat(:,j)=rawData1(2+i:nx+1+i,1);
    i=i+nx;
end
end