nohup FreeFem++-nw  Member1.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member2.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member3.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member4.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member5.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member6.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member7.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member8.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member9.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member10.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member11.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member12.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member13.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member14.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member15.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member16.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member17.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member18.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member19.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member20.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member21.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member22.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member23.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member24.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member25.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member26.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member27.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member28.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member29.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member30.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member31.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member32.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member33.edp > nohup.out 2>&1 &
nohup FreeFem++-nw  Member34.edp > nohup.out 2>&1 &
FreeFem++-nw  Member35.edp
